### PR TITLE
Remove unuse babel-loader

### PR DESCRIPTION
**Pull request by potato4d**
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

- [x] `npm run lint` succeeds.
- [x] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by potato4d** [comment]
build log
```
yarn run v1.12.3
$ npm run build:chrome

> slack-emoji-meister@0.0.2 build:chrome /Users/JP24711/Desktop/Clients/github.com/takanakahiko/slack-emoji-meister
> gulp pack --production --vendor=chrome

[12:46:42] Requiring external module @babel/register
[12:46:44] Using gulpfile ~/Desktop/Clients/github.com/takanakahiko/slack-emoji-meister/gulpfile.babel.js
[12:46:44] Starting 'pack'...
[12:46:44] Starting 'build'...
[12:46:44] Starting 'clean'...
[12:46:44] Finished 'clean' after 15 ms
[12:46:44] Starting 'manifest'...
[12:46:44] Starting 'scripts'...
[12:46:44] Starting 'styles'...
[12:46:44] Starting 'pages'...
[12:46:44] Starting 'locales'...
[12:46:44] Starting 'images'...
[12:46:44] Starting 'fonts'...
[12:46:44] Starting 'chromereload'...
[12:46:44] Starting 'styles:css'...
[12:46:44] Starting 'styles:less'...
[12:46:44] Starting 'styles:sass'...
[12:46:44] Finished 'chromereload' after 15 ms
[12:46:44] Finished 'fonts' after 30 ms
[12:46:44] Finished 'styles:css' after 24 ms
[12:46:44] Finished 'styles:less' after 24 ms
[12:46:44] Finished 'manifest' after 281 ms
[12:46:44] Finished 'pages' after 611 ms
[12:46:44] Finished 'locales' after 640 ms
[12:46:44] Finished 'styles:sass' after 631 ms
[12:46:44] Finished 'styles' after 641 ms
[12:46:46] gulp-imagemin: Minified 4 images (saved 2.44 kB - 31.4%)
[12:46:46] Finished 'images' after 2.13 s
[12:46:46] Finished '[36mscripts[39m' Hash: [1m850b8b4d37538f67e157[39m[22m
Version: webpack [1m4.28.3[39m[22m
Time: [1m1961[39m[22mms
Built at: 01/17/2019 [1m12:46:46 PM[39m[22m
           [1mAsset[39m[22m        [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m[1mChunk Names[39m[22m
   [1m[32mbackground.js[39m[22m    7.46 KiB       [1m0[39m[22m  [1m[32m[emitted][39m[22m  background
[1m[32mcontentscript.js[39m[22m  1010 bytes       [1m1[39m[22m  [1m[32m[emitted][39m[22m  contentscript
      [1m[32moptions.js[39m[22m  1000 bytes       [1m2[39m[22m  [1m[32m[emitted][39m[22m  options
        [1m[32mpopup.js[39m[22m  1000 bytes       [1m3[39m[22m  [1m[32m[emitted][39m[22m  popup
Entrypoint [1mbackground[39m[22m = [1m[32mbackground.js[39m[22m
Entrypoint [1mcontentscript[39m[22m = [1m[32mcontentscript.js[39m[22m
Entrypoint [1moptions[39m[22m = [1m[32moptions.js[39m[22m
Entrypoint [1mpopup[39m[22m = [1m[32mpopup.js[39m[22m
[0] [1mmulti ./app/scripts/background.ts[39m[22m 28 bytes {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[1] [1m./app/scripts/background.ts[39m[22m 4.04 KiB {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[2] [1m./app/scripts/sub_modules/slack.ts[39m[22m 5.49 KiB {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[3] [1m./app/scripts/sub_modules/util.ts[39m[22m 3.77 KiB {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[4] [1mmulti ./app/scripts/contentscript.ts[39m[22m 28 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[5] [1m./app/scripts/contentscript.ts[39m[22m 128 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[6] [1mmulti ./app/scripts/options.ts[39m[22m 28 bytes {[1m[33m2[39m[22m}[1m[32m [built][39m[22m
[7] [1m./app/scripts/options.ts[39m[22m 121 bytes {[1m[33m2[39m[22m}[1m[32m [built][39m[22m
[8] [1mmulti ./app/scripts/popup.ts[39m[22m 28 bytes {[1m[33m3[39m[22m}[1m[32m [built][39m[22m
[9] [1m./app/scripts/popup.ts[39m[22m 119 bytes {[1m[33m3[39m[22m}[1m[32m [built][39m[22m
[12:46:46] Finished 'scripts' after 2.59 s
[12:46:46] Finished 'build' after 2.6 s
[12:46:46] Starting '<anonymous>'...
[12:46:46] Packed [35mdist/chrome[39m to [35m./packages/slack-emoji-meister-0.0.2-chrome.zip[39m
[12:46:46] Finished '<anonymous>' after 121 ms
[12:46:46] Finished 'pack' after 2.72 s
Done in 5.20s.
```

**Comment by potato4d** [comment]
build log
```
yarn run v1.12.3
$ npm run build:chrome

> slack-emoji-meister@0.0.2 build:chrome /Users/potato4d/Desktop/Clients/github.com/takanakahiko/slack-emoji-meister
> gulp pack --production --vendor=chrome

[12:46:42] Requiring external module @babel/register
[12:46:44] Using gulpfile ~/Desktop/Clients/github.com/takanakahiko/slack-emoji-meister/gulpfile.babel.js
[12:46:44] Starting 'pack'...
[12:46:44] Starting 'build'...
[12:46:44] Starting 'clean'...
[12:46:44] Finished 'clean' after 15 ms
[12:46:44] Starting 'manifest'...
[12:46:44] Starting 'scripts'...
[12:46:44] Starting 'styles'...
[12:46:44] Starting 'pages'...
[12:46:44] Starting 'locales'...
[12:46:44] Starting 'images'...
[12:46:44] Starting 'fonts'...
[12:46:44] Starting 'chromereload'...
[12:46:44] Starting 'styles:css'...
[12:46:44] Starting 'styles:less'...
[12:46:44] Starting 'styles:sass'...
[12:46:44] Finished 'chromereload' after 15 ms
[12:46:44] Finished 'fonts' after 30 ms
[12:46:44] Finished 'styles:css' after 24 ms
[12:46:44] Finished 'styles:less' after 24 ms
[12:46:44] Finished 'manifest' after 281 ms
[12:46:44] Finished 'pages' after 611 ms
[12:46:44] Finished 'locales' after 640 ms
[12:46:44] Finished 'styles:sass' after 631 ms
[12:46:44] Finished 'styles' after 641 ms
[12:46:46] gulp-imagemin: Minified 4 images (saved 2.44 kB - 31.4%)
[12:46:46] Finished 'images' after 2.13 s
[12:46:46] Finished '[36mscripts[39m' Hash: [1m850b8b4d37538f67e157[39m[22m
Version: webpack [1m4.28.3[39m[22m
Time: [1m1961[39m[22mms
Built at: 01/17/2019 [1m12:46:46 PM[39m[22m
           [1mAsset[39m[22m        [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m[1mChunk Names[39m[22m
   [1m[32mbackground.js[39m[22m    7.46 KiB       [1m0[39m[22m  [1m[32m[emitted][39m[22m  background
[1m[32mcontentscript.js[39m[22m  1010 bytes       [1m1[39m[22m  [1m[32m[emitted][39m[22m  contentscript
      [1m[32moptions.js[39m[22m  1000 bytes       [1m2[39m[22m  [1m[32m[emitted][39m[22m  options
        [1m[32mpopup.js[39m[22m  1000 bytes       [1m3[39m[22m  [1m[32m[emitted][39m[22m  popup
Entrypoint [1mbackground[39m[22m = [1m[32mbackground.js[39m[22m
Entrypoint [1mcontentscript[39m[22m = [1m[32mcontentscript.js[39m[22m
Entrypoint [1moptions[39m[22m = [1m[32moptions.js[39m[22m
Entrypoint [1mpopup[39m[22m = [1m[32mpopup.js[39m[22m
[0] [1mmulti ./app/scripts/background.ts[39m[22m 28 bytes {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[1] [1m./app/scripts/background.ts[39m[22m 4.04 KiB {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[2] [1m./app/scripts/sub_modules/slack.ts[39m[22m 5.49 KiB {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[3] [1m./app/scripts/sub_modules/util.ts[39m[22m 3.77 KiB {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
[4] [1mmulti ./app/scripts/contentscript.ts[39m[22m 28 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[5] [1m./app/scripts/contentscript.ts[39m[22m 128 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
[6] [1mmulti ./app/scripts/options.ts[39m[22m 28 bytes {[1m[33m2[39m[22m}[1m[32m [built][39m[22m
[7] [1m./app/scripts/options.ts[39m[22m 121 bytes {[1m[33m2[39m[22m}[1m[32m [built][39m[22m
[8] [1mmulti ./app/scripts/popup.ts[39m[22m 28 bytes {[1m[33m3[39m[22m}[1m[32m [built][39m[22m
[9] [1m./app/scripts/popup.ts[39m[22m 119 bytes {[1m[33m3[39m[22m}[1m[32m [built][39m[22m
[12:46:46] Finished 'scripts' after 2.59 s
[12:46:46] Finished 'build' after 2.6 s
[12:46:46] Starting '<anonymous>'...
[12:46:46] Packed [35mdist/chrome[39m to [35m./packages/slack-emoji-meister-0.0.2-chrome.zip[39m
[12:46:46] Finished '<anonymous>' after 121 ms
[12:46:46] Finished 'pack' after 2.72 s
Done in 5.20s.
```

**Comment by takanakahiko** [comment]
This repository was created using [generator-chrome-extension-kickstart-typescript](https://github.com/mazamachi/generator-chrome-extension-kickstart-typescript) .
That template is a fork of [generator-chrome-extension-kickstart](https://github.com/HaNdTriX/generator-chrome-extension-kickstart).

When migrating to typescript (`babel-loader` to` ts-loader`), I think that I forgot to delete the package in template.

**Comment by takanakahiko** [comment]
Thanks!

**Pull request merged**
